name: 'Modelix URL'
description: 'Adds a link to the current diff on your modelix instance to every pull request.'
branding:
  icon: 'link'
  color: 'blue'
inputs:
    repo-token:
      description: 'The GITHUB_TOKEN secret'
    modelix-url:
      description: 'Root url of the modelix instance running the diff service.'

runs:
  using: 'node12'
  main: 'dist/index.js'
